version: '3.8'
services: 
  node-webpack-ejs:
    restart: always 
    build: 
      context: .
      dockerfile: ./images/Dockerfile
    volumes: 
      - /app/node_modules
      - ./www:/app 
    ports: 
      - "3006:3000"
